### PR TITLE
Add compat for Tables/TableTraits

### PR DESCRIPTION
**Pull request by sethaxen**
Forgot to include version bounds in #193 .

### CODE REVIEW

**Comment by devmotion** [comment]
Are you sure that it works with the old versions and do you think compatibility is needed? I'm wondering since Travis just runs test with the most recent versions.

**Comment by sethaxen** [comment]
> Are you sure that it works with the old versions and do you think compatibility is needed? I'm wondering since Travis just runs test with the most recent versions.

Pretty sure. I tested locally with the old versions of TableTraits/IteratorInterfaceExtensions, and tests passed. Also, the documentation RE how to implement the interface did not change from the old to new versions. Finally, to identify the functions to overload, I used as my reference DataFrames, which also indicates compatibility with the same older versions.

**Comment by devmotion** [comment]
OK, perfect!

**Comment by devmotion** [comment]
Thanks a lot!

**Comment by sethaxen** [comment]
You're welcome!

**Pull request merged**
