### PR TITLE
Make group more general

### PR DESCRIPTION
**Pull request by itsdfish**
Hi, 

I noticed that `group` does not work with Stan's default "." indexing. I added a groupby argument that allows group to work with Stan or any other arbitrary indexing. The default is Turings "[]" indexing. Thus, no breaking changes were introduced.

### CODE REVIEW

**Comment by itsdfish** [comment]
Hello,

I tried using this with StanSample and noticed that it has not be merged into MCMCChains. Would it be possible to merge and release a new version?

**Comment by cpfiffer** [comment]
Yeah, happy to merge after tests pass.

**Comment by itsdfish** [comment]
@cpfiffer, much appreciated!

**Comment by cpfiffer** [comment]
@itsdfish all merged, should be good now!

**Pull request merged**
