### PR TITLE
Set version to 5.0.3

### PR DESCRIPTION
**Pull request by cpfiffer**

### CODE REVIEW

**Review by rikhuijzer — APPROVED** [review]

**Comment by rikhuijzer** [comment]
I changed the name because more informative is more better in this case

I see that the MLJBase update (#348) is not registered yet, so I'm gonna go ahead and merge this PR and register a new version.

**Comment by devmotion** [comment]
> I see that the MLJBase update (#348) is not registered yet, so I'm gonna go ahead and merge this PR and register a new version.

The update only fixes tests but doesn't change anything in the package. Only MCMCDiagnosticTools had to be fixed.

**Comment by rikhuijzer** [comment]
> > I see that the MLJBase update (#348) is not registered yet, so I'm gonna go ahead and merge this PR and register a new version.
> 
> The update only fixes tests but doesn't change anything in the package. Only MCMCDiagnosticTools had to be fixed.

Also cleaning up confusion for readers about

image

**Comment by rikhuijzer** [comment]
> The update only fixes tests but doesn't change anything in the package. Only MCMCDiagnosticTools had to be fixed.

But, you're right. I didn't notice that MLJBase was only updated in `test/Project.toml`. Registering this package was not necessary. I'll check better next time.

**Pull request merged**
