### PR TITLE
keep parameter order

### PR DESCRIPTION
**Pull request by a1ix2**
Addresses https://github.com/TuringLang/MCMCChains.jl/issues/443

### CODE REVIEW

**Comment by mhauru** [comment]
Looks good to me, thanks @a1ix2! Did you run into a case where this caused you trouble? If so, do you have a reproducible example that triggers the issue (even non-minimal)? Would be good to have a test for this too, but the original issue you reference didn't come with an MWE.

**Comment by a1ix2** [comment]
For me it was mostly an annoyance when trying to interoperate with `ComponentArrays` when using `get`. Here's a more or less useless example but still.

```julia
using Turing, Distributions

@model function fakemodel(xs)
    mu1 ~ Normal(10.0)
    mu2 ~ Normal(10.0)
    sigma1 ~ InverseGamma(2.0, 1.0)
    sigma2 ~ InverseGamma(2.0, 1.0)
    for i in eachindex(xs)
        xs[i] ~ MixtureModel([Normal(mu1, sigma1), Normal(mu2, sigma2)], [0.5, 0.5])
    end
end

xs = rand(MixtureModel([Normal(0.1, 1.0), Normal(3.0, 0.5)], [0.5, 0.5]), 1000)

model = fakemodel(xs)

chain = sample(model, NUTS(), 100)

all_chains = get_params(chain)
keys(allchains)
# which returns an NTuple with a jumble of unordered internal and parameters
# (:hamiltonian_energy, :n_steps, :numerical_error, :max_hamiltonian_energy_error, :mu2, :sigma1, :hamiltonian_energy_error, :mu1, :is_accept, :sigma2, :log_density, :tree_depth, :step_size, :acceptance_rate, :lp, :nom_step_size)

all_param_chains = get(chain, section=:parameters)
# Also returns a NamedTuple with unordered parameters
# (mu1 = [0.16170966805695142; 0.1554824980047796; … ; 0.08014927911102815; 0.0922168468995448;;], mu2 = [2.9505553517683385; 3.0352436810243066; … ; 2.9597771408952247; 2.9428157073776444;;], sigma2 = [0.549196145152957; 0.5526604135099159; … ; 0.5646327205926919; 0.6056774396897618;;], sigma1 = [0.8824624114147762; 0.9787977609583128; … ; 0.9162592661201038; 0.931760395213333;;])

keys(all_param_chains)
# (:mu1, :mu2, :sigma2, :sigma1)
```

Ideally I'd want to obtain a chain as a vector of ComponentArrays, one for each iteration, so that I can splat more easily into other blackbox optimizers like CMAEvolutionStrategy and so on. Right now I have to rely on writing a return statement in the model with all parameters manually listed

```julia
using ComponentArrays: ComponentArray

@model function fakemodel_ret(xs)
    mu1 ~ Normal(10.0)
    mu2 ~ Normal(10.0)
    sigma1 ~ InverseGamma(2.0, 1.0)
    sigma2 ~ InverseGamma(2.0, 1.0)
    for i in eachindex(xs)
        xs[i] ~ MixtureModel([Normal(mu1, sigma1), Normal(mu2, sigma2)], [0.5, 0.5])
    end
    
    return ComponentArray(mu1=mu1, mu2=mu2, sigma1=sigma1, sigma2=sigma2
end

model_ret = fakemodel_ret(xs)

chain_ret = sample(model_ret, NUTS(), 100)

qs = generated_quantities(model_ret, chain_ret)
```

or if I want a flat vector of the best chain samples I use something like
```
_bestidx = findmax(chain.value[var=:log_density])[2][1]
_bestsample = chain.value[_bestidx, 1:end-12, 1]
```
where the `end-12` skips the 12 internals (I _think_ this number is dependent on the particular sampler?), but this gives me an AxisArray I can't easily cast into a ComponentArray (which I find much more intuitive to deal with).

While I haven't yet figured out a way to cleanly do these kinds of things using MCMCChains.jl this was the first

**Review by mhauru — APPROVED** [review]
I added a test that covers the changes here. Thanks @a1ix2, much appreciated!

**Review by radka-j — APPROVED** [review]
LGTM :)

**Comment by mhauru** [comment]
Live once [v6.0.7](https://github.com/JuliaRegistries/General/pull/120833) is out.

**Pull request merged**
