### PR TITLE
Remove preset for ESS

### PR DESCRIPTION
**Pull request by cpfiffer**
Addresses #112, hopefully. @goedman or @itsdfish do you guys have a script handy for comparing CmdStan and MCMCChains ESS draws?

### CODE REVIEW

**Comment by xukai92** [comment]
This a script shared by them before. It does have some plots that comapres different ESS implementations.
[diag_test.jl.zip](https://github.com/TuringLang/MCMCChains.jl/files/3437727/diag_test.jl.zip)

**Comment by goedman** [comment]
Hi Cameron, did I miss this? Let me know, I'm sure I still have this comparison script around somewhere. Is this related to the negative correlation discussion? In fact @xukai92 should work and I can easily try it again.

**Comment by cpfiffer** [comment]
No, you didn't miss it. This PR created a different problem, where the ESS seems to be fixed at a lower level than the Stan ESS. I'm not quite sure what's up.

**Comment by cpfiffer** [comment]
Closed in favor of #122.

**Pull request closed without merging**
