### PR TITLE
Add set_names to README

### PR DESCRIPTION
**Pull request by itsdfish**
I had trouble finding `set_names` and noticed it was not in the documentation.

### CODE REVIEW

**Comment by itsdfish** [comment]
I'm not sure exactly what happened here. It looks like it could not install Julia. I don't think the changes to the docs would have caused the problem.

**Comment by goedman** [comment]
HI Chris, I think this is a broader Julia on Travis issue. All Travis installs for Julia seem to fail.

**Comment by itsdfish** [comment]
Yikes. That's no good. Thanks for the info.

**Comment by cpfiffer** [comment]
Since there's no functional change, I'll just merge this over. Thanks, Chris!

**Pull request merged**
