### PR TITLE
Remove Turing from dataframe/summarize tests

### PR DESCRIPTION
**Pull request by cpfiffer**
Builds on Turing master and AdvancedHMC master are failing. I think it's a good idea to remove Turing from the summarize and DataFrame constructor tests since Turing's internals has had and will maybe continue to have some changes.

### CODE REVIEW

**Comment by goedman** [comment]
Hi Cameron, that’s fine. Is that also the case for DynamicNUTS variant as far as you know?

**Comment by cpfiffer** [comment]
As far as I'm aware, DynamicNUTS is safe. I will send you a message if I notice that changing, though.

**Comment by goedman** [comment]
Thanks, Chris and I are doing a lot of benchmarking on mcmc and if possible we do like to continue to keep DynamicNUTS in the loop.

**Comment by cpfiffer** [comment]
Yeah, there's no plans to drop it. It's a good implementation and it plays well with our internals, so we're happy to keep it along.

**Comment by cpfiffer** [comment]
Most of what I was referring to with changes have to do with Turing's internal HMC stuff being moved over to AdvancedHMC, which is a lot cleaner and faster than the older stuff. It doesn't use the same `:internals` parameters as Turing's original HMC stuff. Don't worry -- we're not going to run around and break everything.

**Comment by goedman** [comment]
You've been pretty solid in that respect (and others), so I'm not worried. It is interesting to see how much is changing in Julia's mcmc world! Good stuff!

**Pull request merged**
